# Generated by Django 4.0.4 on 2022-07-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ttt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ttt',
        ),
    ]
