# Generated by Django 4.0.4 on 2023-01-08 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220808_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', '-created', 'subject']},
        ),
    ]
