# Generated by Django 4.0.4 on 2023-01-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
    ]
