# Generated by Django 4.0.4 on 2023-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='users.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
