# Generated by Django 4.0.4 on 2023-01-16 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_alter_profile_reviews_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
