# Generated by Django 4.0.4 on 2023-01-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-reviews_counter']},
        ),
    ]
