# Generated by Django 4.0.4 on 2023-01-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
