# Generated by Django 4.0.4 on 2023-01-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_saved',
        ),
    ]
