# Generated by Django 4.0.4 on 2023-01-29 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0022_alter_profile_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reviews',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
