# Generated by Django 4.0.4 on 2023-01-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profile_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reviews',
            field=models.ManyToManyField(to='users.profile'),
        ),
    ]
