# Generated by Django 4.0.4 on 2022-05-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_vote_ratio_project_vote_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to=''),
        ),
    ]
