# Generated by Django 4.0.4 on 2023-01-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
